DROP TABLE IF EXISTS recruiter_configuration;
DROP TABLE IF EXISTS usercommon;
DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS searchingsuggestion;
DROP TABLE IF EXISTS ward;
DROP TABLE IF EXISTS district;
DROP TABLE IF EXISTS province;

CREATE TABLE province (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  code VARCHAR(255),
  isactive BOOLEAN,
  createdat TIMESTAMP,
  updatedat TIMESTAMP,
  createdby VARCHAR(4000),
  providers VARCHAR(4000),
  lat DOUBLE,
  lng DOUBLE
);

CREATE TABLE district (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  provincecode VARCHAR(255),
  code VARCHAR(255),
  isactive BOOLEAN,
  createdat TIMESTAMP,
  updatedat TIMESTAMP,
  createdby VARCHAR(4000),
  providers VARCHAR(4000),
  lat DOUBLE,
  lng DOUBLE
);

CREATE TABLE ward (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  provincecode VARCHAR(255),
  code VARCHAR(255),
  isactive BOOLEAN,
  createdat TIMESTAMP,
  updatedat TIMESTAMP,
  createdby VARCHAR(4000),
  providers VARCHAR(4000),
  lat DOUBLE,
  lng DOUBLE
);

CREATE TABLE organization (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  des VARCHAR(255),
  creationdate TIMESTAMP,
  updatedate TIMESTAMP,
  active INTEGER,
  avatar VARCHAR(255),
  province VARCHAR(255),
  ward VARCHAR(255),
  website VARCHAR(255),
  industry VARCHAR(255)
);

CREATE TABLE usercommon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(255),
  pin VARCHAR(255),
  status VARCHAR(255),
  totalmoney DOUBLE,
  rating INTEGER,
  role INTEGER,
  loginnumber BIGINT,
  withdrawnumber INTEGER,
  introphone VARCHAR(255),
  email VARCHAR(255),
  avatar VARCHAR(255),
  sentpassword INTEGER,
  facebookid VARCHAR(200),
  googleid VARCHAR(255),
  receiveinfo INTEGER,
  sendsmsnumber INTEGER,
  creationdate TIMESTAMP,
  updatedate TIMESTAMP,
  dateofbirth TIMESTAMP,
  country VARCHAR(255),
  nationality VARCHAR(255),
  detailaddress VARCHAR(255),
  premiumexpdate TIMESTAMP,
  name VARCHAR(255),
  gender VARCHAR(255),
  address VARCHAR(255),
  jobtarget VARCHAR(255),
  experience VARCHAR(255),
  province VARCHAR(255),
  ward VARCHAR(255),
  organizationid BIGINT,
  packageid BIGINT,
  active INTEGER,
  ispremium BOOLEAN
);

CREATE TABLE recruiter_configuration (
  cus_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT,
  status VARCHAR(255)
);

CREATE TABLE searchingsuggestion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  val VARCHAR(255),
  rank INTEGER,
  object VARCHAR(10),
  creationdate TIMESTAMP,
  updatedate TIMESTAMP
);
